### ISSUE TITLE
使用出问题

### ISSUE THREAD

**Issue by simplefeel** [jerryshew/react-image-cropper#1]
我按教程使用，初始显示：
![image](https://cloud.githubusercontent.com/assets/9206408/18829117/683bd7ec-840d-11e6-95ba-217aeb84be94.png)

之后 移动裁剪框，选中区域和裁剪框内显示不一致错乱，
![image](https://cloud.githubusercontent.com/assets/9206408/18829124/6f23d910-840d-11e6-9fbe-9d0e5f9507fb.png)

点击裁剪按钮，显示如下:
![image](https://cloud.githubusercontent.com/assets/9206408/18829126/75d43ec6-840d-11e6-95e3-24b614eb7854.png)

请问改如何解决呢~~

**Comment by jerryshew** [comment]
你是用什么浏览器？

**Comment by jerryshew** [comment]
@simplefeel 你用的什么浏览器？拖拽时显示有问题？
