### ISSUE TITLE
Add Changelog/Release notes, or named releases

### ISSUE THREAD

**Issue by mbifulco** [jerryshew/react-image-cropper#15]
Hi @jerryshew - thanks for the useful library.

I'm just going through my project's dependencies, and saw that you pushed an updated version # recently, which got released to NPM.  Currently there's no changelog to look at, to see what changes have been added to the package since the last release.  It's common to include release notes in a `Changelog.md` file in the repo, or in the description of a named release on the `/releases` page of GitHub here, to help users of your repo understand whether or not updates to your package include breaking changes.

Can you add releases for this package, so that we can better keep track?
![image](https://user-images.githubusercontent.com/1844496/29275612-b81deaa6-80d9-11e7-9b51-8049fbd5315d.png)

Right now my only option is to look through individual commits since your last release, which may mean I miss something.

Thanks!

**Comment by jerryshew** [comment]
ok, I will put this on agenda

**Comment by mbifulco** [comment]
Thank you! I'm happy to provide help/feedback if you need it.
