### ISSUE TITLE
Do you guys support cropping animated gifs?

### ISSUE THREAD

**Issue by puffstream** [jerryshew/react-image-cropper#20]
Library works really well with png and jpegs, can't seem to get it working for gif animations.

Thanks!

**Comment by puffstream** [comment]
Checked further into your library, looks like your using Canvas and doesn't look like Canvas supports gifs, suggestions in the community on how to remedy this but we might go with some other options. Thanks!

**Comment by jerryshew** [comment]
@puffstream yes, canvas not support gif
