### ISSUE TITLE
图片显示问题！！！

### ISSUE THREAD

**Issue by LynnHg** [jerryshew/react-image-cropper#27]
`<Cropper
                    src={this.state.imageUrl}
                    width={1280}
                    height={800}
                    ratio={16 / 10}
                    onChange={() => this.handleCropOnChange('image')}
                    ref={ref => (this.image = ref)}
                    onImgLoad={() => this.handleImageLoaded('image')}
                  />`
第一次裁剪正常:
![image](https://user-images.githubusercontent.com/18587596/34511010-c42e6c92-f093-11e7-9e46-84ec46eff988.png)
当我删除上传的图片，再次上传图片时，Cropper组件似乎会记忆上一次用户的操作，比如：
显示裁剪：
![image](https://user-images.githubusercontent.com/18587596/34511076-15329172-f094-11e7-81b7-542f8a5165c2.png)
裁剪完成预览确实这样：
![image](https://user-images.githubusercontent.com/18587596/34511087-2869983a-f094-11e7-8197-9be084d1ddde.png)
再比如：
本次裁剪我改变裁剪框的大小，然后裁剪
![image](https://user-images.githubusercontent.com/18587596/34511118-5e860322-f094-11e7-86ac-1b345f8b9721.png)
当删除图片，再次上传图片时，记忆了上一次裁剪框的大小
![image](https://user-images.githubusercontent.com/18587596/34511141-8dd5f768-f094-11e7-878e-9236346ea9e1.png)
如何解决？

**Comment by LynnHg** [comment]
图片也不是按照比例缩放。

**Comment by jerryshew** [comment]
原因是图片更新未重新计算尺寸，后续会修复

**Comment by jerryshew** [comment]
请升级 https://github.com/jerryshew/react-image-cropper/commit/3a2a2d49cade2ee4e36c734ebaeb9b676aa0b151 版本
