### ISSUE TITLE
cropper container resizes image

### ISSUE THREAD

**Issue by supromikali** [jerryshew/react-image-cropper#29]
@jerryshew Thanks for this lib! Works really nice and has clear API.

I have found that image-cropper can work fine with responsive image container but it also has unwanted behavior.

When I do crop image with original size say 1200x2400 in a container that is 360px width the resulting image width is also 360px and not 1200px as I expect. Could you advise any workaround on this, please?

**Comment by GeorgeBarnard** [comment]
I have also come across this issue today, any workaround would be great.

**Comment by supromikali** [comment]
@GeorgeBarnard Currently I use readAsDataURL after getting a file from file input

**Comment by GeorgeBarnard** [comment]
@supromikali Yeah, that's exactly what I am doing. After looking in the plugin It would seem that its ignoring .naturalWidth / .naturalHeight and just using the container size as a reference. At least it is for me, but I may be doing something completely wrong. Did you get any further?

**Comment by julensas** [comment]
Same here :/

**Comment by jerryshew** [comment]
@supromikali @GeorgeBarnard @julensas this is a bug, I will fix this later.

**Comment by jerryshew** [comment]
resloved at this version: https://github.com/jerryshew/react-image-cropper/commit/3a2a2d49cade2ee4e36c734ebaeb9b676aa0b151

**Comment by ghost** [comment]
this is still happening for me https://imgur.com/a/ip8ncbP
