### ISSUE TITLE
Cropper options

### ISSUE THREAD

**Issue by oyeanuj** [jerryshew/react-image-cropper#3]
Hi @jerryshew! Thank you for open sourcing this useful library. Wondering if there are configuration options for the following - 

1. Have a circular cropper instead of square or rectangle?
2. Have the cropper centered on the image when initialized?

Thanks!

**Comment by jerryshew** [comment]
@oyeanuj 
1. not plain to do this
2. can do, but I recently have no time

you can create a pull request.

**Comment by oyeanuj** [comment]
@jerryshew for 2, can you provide me some starting guidance since you know the code best?

**Comment by jerryshew** [comment]
@oyeanuj ok, i will add some comments, apologize for replying too late.

**Comment by jerryshew** [comment]
@oyeanuj add comments to each function and some statements.
